# -*- coding: utf-8 -*-
"""facerecog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpKfeCahL6Q-N6OBX0B9AXDHiOEgrSd2
"""

#!pip install face_recognition

import face_recognition
import cv2
import os
TOLERANCE = 0.6 
FRAME_THICKNESS = 3
FONT_THICKNESS = 2
MODEL = "cnn"

known_faces = []
known_names = []
for name in os.listdir("Known"):
  for imagepath in os.listdir(f"Known/{name}"):
      image = face_recognition.load_image_file(f"Known/{name}/{imagepath}")
      enc = face_recognition.face_encodings(image)[0]
      known_faces.append(enc)
      known_names.append(name)

for files in os.listdir("Unknown"):
  image = face_recognition.load_image_file(f"Unknown/{files}")
  locations = face_recognition.face_locations(image, model= MODEL)  
  encodings = face_recognition.face_encodings(image, locations)
  image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
  for location, encoding in zip(locations, encodings):
    res = face_recognition.compare_faces(known_faces, encoding, tolerance=TOLERANCE)
    match = None
    if True in res:
      match = known_names[res.index(True)]
      print(f"Match: {match}")
      top_left = (location[3], location[0])
      bot_right = (location[1],location[2])
      color = [0,255,0]
      cv2.rectangle(image, top_left, bot_right, color, FRAME_THICKNESS)
      top_left = (location[3], location[2])
      bot_right = (location[1],location[2] + 20)
      cv2.rectangle(image, top_left, bot_right, color, cv2.FILLED)
      cv2.putText(image, match, (location[3]+10, location[2]+7), cv2.FONT_HERSHEY_SIMPLEX, 0.5,(200,200,200), FONT_THICKNESS)

  cv2.imshow(files, image)
  cv2.waitkey(0)
  cv2.destroywindow(files)